# Data sources and final report {#daten-und-bericht}

```{block, type = 'rmdoutcomes'}
- Know different data sources
- Use libraries for direct access to databases
```

## Data sources

In this chapter, I will introduce some interesting data sources (databases) that you can use for your final report. I offer technical assistance for the package `eurostat`. You can discover other packages on your own (this could be a possible challenge for the final report, see below `r emo::ji('smile')`).


### Federal Statistical Office
The [Federal Statistical Office](https://www.destatis.de/EN/Home/_node.html) offers data about Germany in different areas through their database 
 [GENESIS](https://www-genesis.destatis.de/genesis/online?operation=previous&levelindex=&step=&titel=&levelid=&acceptscookies=false). You can navigate to the data sets and download them. Pay attention to select the format **flat** when downloading to get a *tidy* data set.

### eurostat
[eurostat](https://ec.europa.eu/eurostat) is the statistical office of the European Union. You will find many different data sets about Europe there. However, I strongly recommend using the dedicated R library [eurostat](http://ropengov.github.io/eurostat/index.html) to download the data. My experience shows that students underestimate how error-prone manual download from a large database can be! The R library eurostat has an informative web site with many tutorials. Some of the show how to use the eurostat data to visualize maps (possible report challenge). 


### gapminder
You already worked with an excerpt of data by [gapminder](https://www.gapminder.org). The complete data set contains much more. You can download more data [here](https://www.gapminder.org/data/). gapminder organises their data in a so-called DDF Format (data description format) as *tidy* .csv files. A possible report challenge could be to understand this format. A complete data set is availagle via GitHub [here](https://github.com/open-numbers/ddf--gapminder--systema_globalis).


### National Oceanic and Atmospheric Administration (NOAA)
[NOAA](https://www.noaa.gov/) offers data on oceans, climate and weather. You can download the data sets via the library  [rnoaa](https://docs.ropensci.org/rnoaa/).


### More data sources
- [World Bank Open Data](https://data.worldbank.org/)
- [World Happiness Report](https://worldhappiness.report/ed/2021/)
- Global Carbon Budget 2020
  - [Publication and data set](https://essd.copernicus.org/articles/12/3269/2020/)
  - [Global Carbon Project](https://www.globalcarbonproject.org/index.htm)
- Soil organic carbon contents from sites under perennial cultivation
  - [Publication](https://www.nature.com/articles/s41597-019-0062-1)
  - [Data set](https://figshare.com/articles/dataset/A_global_empirical_harmonised_dataset_of_Soil_Organic_Carbon_under_Perennial_Crops/7637210)
- [PANGAEA](https://www.pangaea.de/): one of the largest databases for environmental datasets
- Overview of data and libraries on [ROpenScie](https://ropensci.org/):
  [Data](https://github.com/ropensci-archive/opendata)
  [Libraries](https://ropensci.org/packages/data-access/)

## Research proposal
Before you write your final report, you need to submit a research proposal on ILIAS. **Be sure to upload before the deadline!**. You will receive feedback on it. This should avoid any misunderstanding about your final report. Please use the template provided on ILIAS for the research proposal.


## Structure of the final report
### Structure of the working directory
Create a new **R project** for your final report. You can find more about using projects [here](https://support.rstudio.com/hc/en-us/articles/200526207-Using-Projects). A project helps you to structure your work properly.

Inside your project folder, create a folder for Data and Notebooks, and additional folders if required.

### Download and save data
If you want to use libraries to download data, then create a notebook for this task. Don't download and analyse the data on-the-fly. Data can change and there will be a time delay between your analysis and my assessment of your report. Download and save your data in the data folder. Use the saved data for the analysis. This will ensure that your report is **fully reproducible**.

### Structure of the report
Please structure your report as follows:

  - Introduction (with research question at the end)
  - Material and Methods: 
      - Data description:
      date of download, **reproducibility** is crucial), description of variables and their units
      - Description of the method with references, description of the research area if appropriate 
  - Results: 
      - Explorative data analysis (mandatory!)
      - Further analysis to respond to your research question(s)
  - Discussion: use peer-reviewed literature to discuss your results
  - Conclusions
  - Bibliography
  
You can combine results and discussion to one section.

Each report should contain a **challenge**. This can be an extensive data tidying and wrangling or use of a new and interesting library (e.g. to plot spatial data in eurostat) etc. provide the outcomes of the challenge in the Results section and discuss them in the Discussion. Ideally, you use the challenge to answer one of your research questions. 

You can write your report in groups of two, I even recommend to do so. In this case, please add your names to the respective parts that you are responsible to receive individual grades. Every part will be graded separately. Every group member need to do some analysis and some writing. Alternatively, give your consent to receive the same grade if you analysed the data and wrote the report together.

I don't impose any particular length for your report. However, please be *concise*.

### Submission
Knit the final report to an html-document. Think about whether you need to show all chunks, avoid redundancy. **Compress the whole R project into a zip-file and submit the zip-file!** Your report and your analysis must run on my computer, so make sure you use relative path directories and test that the script runs on different computers. Also add your draft and final proposal to the Notebooks folder before you submit it.



```{block, type='rmdalert'}
Submit the compressed project to ILIAS before the deadline.
```

## Evaluation critera
The grading follows the evaluation rubric that is available on ILIAS. This rubric contains the following criteria:

1. Does the notebook run without errors?
1. Is the the notebook structured as prescribed above and in the presentation slides on ILIAS?
1. Are the research questions stated clearly and supported with peer-reviewed literature?
1. Are the methods described and necessary literature cited?
1. Were the data downloaded and saved outside the main report in an extra notebook for full reproducibility? In case the data is downloaded by hand, this must be explained in the main report.
1. Is the research area described?
1. Quality of data preparation and exploratory analysis.
1. Quality of the main analysis, which you do to respond to research questions.
1. Quality of figures.
1. Are the results discussed and additional literature cited? This literature should help evaluating and understanding your results.
1. Are the conclusions sound and supported by the data and results?


You will receive a corrected report as feedback.
