<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>9 Linear regression | Environmental Statistics</title>

    <meta name="author" content="Christina Bogner" />
  
   <meta name="description" content="Lecture notes for the course Environmental Statistics in IMES (UoC), based on the material by ModernDive" />
   <meta name="generator" content="placeholder" />
  <meta property="og:title" content="9 Linear regression | Environmental Statistics" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="Lecture notes for the course Environmental Statistics in IMES (UoC), based on the material by ModernDive" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="9 Linear regression | Environmental Statistics" />
  
  <meta name="twitter:description" content="Lecture notes for the course Environmental Statistics in IMES (UoC), based on the material by ModernDive" />
  
  <!-- JS -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fuse.js/6.4.6/fuse.js" integrity="sha512-zv6Ywkjyktsohkbp9bb45V6tEMoWhzFzXis+LrMehmJZZSys19Yxf1dopHx7WzIKxr5tK2dVcYmaCk2uqdjF4A==" crossorigin="anonymous"></script>
  <script src="https://kit.fontawesome.com/6ecbd6c532.js" crossorigin="anonymous"></script>
    <script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link href="libs/bootstrap-4.6.0/bootstrap.min.css" rel="stylesheet" />
    <script src="libs/bootstrap-4.6.0/bootstrap.bundle.min.js"></script>
    <script src="libs/bs3compat-0.3.1/transition.js"></script>
    <script src="libs/bs3compat-0.3.1/tabs.js"></script>
    <script src="libs/bs3compat-0.3.1/bs3compat.js"></script>
    <link href="libs/bs4_book-1.0.0/bs4_book.css" rel="stylesheet" />
    <script src="libs/bs4_book-1.0.0/bs4_book.js"></script>
    <script src="libs/kePrint-0.0.1/kePrint.js"></script>
    <link href="libs/lightable-0.0.1/lightable.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/autocomplete.js/0.38.0/autocomplete.jquery.min.js" integrity="sha512-GU9ayf+66Xx2TmpxqJpliWbT5PiGYxpaG8rfnBEk1LL8l1KGkRShhngwdXK1UgqhAzWpZHSiYPc09/NwDQIGyg==" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/mark.js/8.11.1/mark.min.js" integrity="sha512-5CYOlHXGh6QpOFA/TeTylKLWfB3ftPsde7AnmhuitiTX4K5SqCLBeKro6sPS8ilsz1Q4NRx3v8Ko2IBiszzdww==" crossorigin="anonymous"></script>

  <!-- CSS -->
  <style type="text/css">
    
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  </style>
    <style type="text/css">
    /* Used with Pandoc 2.11+ new --citeproc when CSL is used */
    div.csl-bib-body { }
    div.csl-entry {
      clear: both;
        }
    .hanging div.csl-entry {
      margin-left:2em;
      text-indent:-2em;
    }
    div.csl-left-margin {
      min-width:2em;
      float:left;
    }
    div.csl-right-inline {
      margin-left:2em;
      padding-left:1em;
    }
    div.csl-indent {
      margin-left: 2em;
    }
  </style>
      <link rel="stylesheet" href="style.css" />
    <link rel="stylesheet" href="font-awesome.min.css" />
  
</head>

<body data-spy="scroll" data-target="#toc">

<div class="container-fluid">
<div class="row">
  <header class="col-sm-12 col-lg-3 sidebar sidebar-book">
    <a class="sr-only sr-only-focusable" href="#content">Skip to main content</a>

    <div class="d-flex align-items-start justify-content-between">
      <h1>
        <a href="index.html" title="Summer term 2022">Environmental Statistics</a>:
        <small class="text-muted">Summer term 2022</small>
      </h1>
      <button class="btn btn-outline-primary d-lg-none ml-2 mt-1" type="button" data-toggle="collapse" data-target="#main-nav" aria-expanded="true" aria-controls="main-nav"><i class="fas fa-bars"></i><span class="sr-only">Show table of contents</span></button>
    </div>

    <div id="main-nav" class="collapse-lg">
      <form role="search">
        <input id="search" class="form-control" type="search" placeholder="Search" aria-label="Search">
      </form>

      <nav aria-label="Table of contents">
        <h2>Table of contents</h2>
        <div id="book-toc"></div>

        <div class="book-extra">
          <p><a id="book-repo" href="#">View book source <i class="fab fa-github"></i></a></li></p>
        </div>
      </nav>
    </div>
  </header>

  <main class="col-sm-12 col-md-9 col-lg-7" id="content">
<div id="lin-reg" class="section level1" number="9">
<h1><span class="header-section-number">9</span> Linear regression</h1>
<div class="rmdoutcomes">
<ul>
<li>
Explain the general structure of a linear model.
</li>
<li>
Name the assumption of a linear model.
</li>
<li>
Calculate a simple linear regression in R.
</li>
</ul>
</div>
<p>With this chapter, we start our journey to statistical modelling. Basically, there are two main reasons why one would like to build a statistical model.</p>
<ol style="list-style-type: decimal">
<li><strong>Explicative modelling</strong>: We suppose that there is a relationship between variables and would like to quantify it.</li>
<li><strong>Predictive modelling</strong>: We want to build a model that can (as accurately as possible) predict future values.</li>
</ol>
<p>In this course, we will focus on explicative modelling and work with linear regression models.</p>
<div id="what-is-a-linear-regression-model" class="section level2" number="9.1">
<h2><span class="header-section-number">9.1</span> What is a linear regression model?</h2>
<p>The term <strong>regression</strong> was coined by Francis Galton (1822-1911) who studied the relationship between the height of parents and their children <span class="citation">(<a href="literature-1.html#ref-Fahrmeir2009" role="doc-biblioref">Fahrmeir, Kneib, and Lang 2009</a>)</span>. He showed that taller-than-average parents tended to have children who were smaller than their parents (more towards the average) and smaller-than-average parents tended to have taller children. He called this phenomenon <strong>regression towards the mean</strong>.</p>
<p>A regression model estimates the relationship between a dependent variable, often called <span class="math inline">\(y\)</span> and independent variables (or predictors) often termed <span class="math inline">\(X\)</span>. Note the capital letter <span class="math inline">\(X\)</span> to indicate that it can be a collection of independent variables (a matrix). We try a definition:</p>
<div class="rmddef">
<p>
A <strong>regression model</strong> has the form:
</p>
<p>
<span class="math display"><span class="math display">\[y = f(X) + \varepsilon\]</span></span>
</p>
<ul>
<li>
<span class="math inline"><span class="math inline">\(y\)</span></span>: dependent variable
</li>
<li>
<span class="math inline"><span class="math inline">\(f\)</span></span>: type of relationship
(function)
</li>
<li>
<span class="math inline"><span class="math inline">\(X\)</span></span>: independent variables
(predictors, explanatory variables)
</li>
<li>
<span class="math inline"><span class="math inline">\(\varepsilon\)</span></span>: error term
</li>
</ul>
<p>
If:
</p>
<ul>
<li>
<span class="math inline"><span class="math inline">\(f\)</span></span> linear (effect of predictors
is additive), the model is called <strong>linear regression
model</strong>
</li>
<li>
<span class="math inline"><span class="math inline">\(X\)</span></span> is a single predictor, the
model is called <strong>simple linear regression model</strong>,
otherwise <strong>multiple linear regression model</strong>
</li>
</ul>
<p>
Components of the model:
</p>
<ul>
<li>
<span class="math inline"><span class="math inline">\(f(X)\)</span></span>: systematic or
deterministic component
</li>
<li>
<span class="math inline"><span class="math inline">\(\varepsilon\)</span></span>: stochastic
component (error term, residuals)
</li>
</ul>
</div>
<p>In a regression model, we are not after the exact values of the dependent variable, but after the systematic influence of predictors on the mean value of the dependent variable. Because of the error term (which can contain random fluctuations, measurement errors etc.), the dependent variable <span class="math inline">\(y\)</span> is a <strong>random variable</strong>.</p>
</div>
<div id="simple-linear-regression" class="section level2" number="9.2">
<h2><span class="header-section-number">9.2</span> Simple linear regression</h2>
<p>In case we have one predictor only, the model is a simple linear regression model and its geometric form is a line. A line is defined by its intercept (the point where it cuts the <span class="math inline">\(y\)</span> axis) and its slope. This is exactly the form of a simple linear regression model:</p>
<div class="rmddef">
<p>
Given <strong>data</strong> pairs: <span class="math inline"><span class="math inline">\((y_i,x_i), \quad i=1,\dots,n\)</span></span>
</p>
<p>
<span class="math inline"><span class="math inline">\(y\)</span></span> and <span class="math inline"><span class="math inline">\(x\)</span></span> are numeric variables.
</p>
<p>
We call the model <span class="math display"><span class="math display">\[y_i=\beta_0 +
\beta_1x_i + \varepsilon_i, \qquad i=1,\dots,n.\]</span></span>
</p>
<p>
a <strong>simple linear regression model</strong>, if the errors
<span class="math inline"><span class="math inline">\(\varepsilon_1,\dots, \varepsilon_n\)</span></span>
are independent and identically distributed (iid) and
</p>
<p>
<span class="math display"><span class="math display">\[\mathrm{E}(\varepsilon_i) = 0, \qquad
\mathrm{Var}(\varepsilon_i)=\sigma^2.\]</span></span>
</p>
<p>
If additionally <span class="math display"><span class="math display">\[\varepsilon_i \sim
N(0,\sigma^2)\]</span></span>
</p>
<p>
i.e. the residuals are normally distributed, we call the model a
<strong>normal linear regression model</strong>.
</p>
<p>
<span class="math inline"><span class="math inline">\(\beta_0\)</span></span> is the intercept and
<span class="math inline"><span class="math inline">\(\beta_1\)</span></span> the slope of the model.
</p>
</div>
<p>The assumptions of the normal linear regression model can be summarized as LINE:</p>
<ol style="list-style-type: decimal">
<li><strong>L</strong>inear relationship between variables</li>
<li><strong>I</strong>ndependence of residuals</li>
<li><strong>N</strong>ormal residuals</li>
<li><strong>E</strong>quality of variance (called homoscedasticity) and a mean of zero in residuals</li>
</ol>
<p>Before you look at the model results, the confidence intervals of the slope or the intercept, you have to ensure that those assumptions are met!</p>
</div>
<div id="example-relationship-between-the-time-in-the-library-and-the-travel-time" class="section level2" number="9.3">
<h2><span class="header-section-number">9.3</span> Example: Relationship between the time in the library and the travel time</h2>
<p>We come back to our lovely getsmarter university and want to study the relationship between the time a student needs to come to the university and the time she spends in the library.</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="lin-reg.html#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb145-2"><a href="lin-reg.html#cb145-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span>
<span id="cb145-3"><a href="lin-reg.html#cb145-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(moderndive)</span>
<span id="cb145-4"><a href="lin-reg.html#cb145-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code></pre></div>
<p>Let’s generate the population.</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="lin-reg.html#cb146-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb146-2"><a href="lin-reg.html#cb146-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-3"><a href="lin-reg.html#cb146-3" aria-hidden="true" tabindex="-1"></a>student_id <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">12000</span></span>
<span id="cb146-4"><a href="lin-reg.html#cb146-4" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb146-5"><a href="lin-reg.html#cb146-5" aria-hidden="true" tabindex="-1"></a>travel_time <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">runif</span>(<span class="at">n =</span> <span class="dv">12000</span> <span class="sc">*</span> <span class="fl">0.8</span>, <span class="at">min =</span> <span class="dv">5</span>, <span class="at">max =</span> <span class="dv">40</span>),</span>
<span id="cb146-6"><a href="lin-reg.html#cb146-6" aria-hidden="true" tabindex="-1"></a>             <span class="fu">runif</span>(<span class="at">n =</span> <span class="dv">12000</span> <span class="sc">*</span> <span class="fl">0.2</span>, <span class="at">min =</span> <span class="dv">60</span>, <span class="at">max =</span> <span class="dv">120</span>))</span>
<span id="cb146-7"><a href="lin-reg.html#cb146-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-8"><a href="lin-reg.html#cb146-8" aria-hidden="true" tabindex="-1"></a>gender <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&#39;m&#39;</span>, <span class="st">&#39;f&#39;</span>), <span class="at">size =</span> <span class="dv">12000</span>, <span class="at">replace =</span> <span class="cn">TRUE</span>)</span>
<span id="cb146-9"><a href="lin-reg.html#cb146-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-10"><a href="lin-reg.html#cb146-10" aria-hidden="true" tabindex="-1"></a>residence <span class="ot">&lt;-</span> <span class="fu">sapply</span>(travel_time, <span class="cf">function</span>(x) {</span>
<span id="cb146-11"><a href="lin-reg.html#cb146-11" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(x <span class="sc">&lt;</span> <span class="dv">30</span>) <span class="st">&#39;urban&#39;</span></span>
<span id="cb146-12"><a href="lin-reg.html#cb146-12" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span> <span class="st">&#39;rural&#39;</span></span>
<span id="cb146-13"><a href="lin-reg.html#cb146-13" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb146-14"><a href="lin-reg.html#cb146-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-15"><a href="lin-reg.html#cb146-15" aria-hidden="true" tabindex="-1"></a>transport <span class="ot">&lt;-</span> <span class="fu">sapply</span>(travel_time, <span class="cf">function</span>(x) {</span>
<span id="cb146-16"><a href="lin-reg.html#cb146-16" aria-hidden="true" tabindex="-1"></a>  <span class="cf">if</span>(x <span class="sc">&lt;=</span> <span class="dv">10</span>) <span class="st">&#39;foot&#39;</span></span>
<span id="cb146-17"><a href="lin-reg.html#cb146-17" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span> <span class="cf">if</span>(x <span class="sc">&gt;</span> <span class="dv">10</span> <span class="sc">&amp;</span> x <span class="sc">&lt;=</span> <span class="dv">15</span>) <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&#39;foot&#39;</span>, <span class="st">&#39;bike&#39;</span>), <span class="at">size =</span> <span class="dv">1</span>)</span>
<span id="cb146-18"><a href="lin-reg.html#cb146-18" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span> <span class="cf">if</span>(x <span class="sc">&gt;</span> <span class="dv">15</span> <span class="sc">&amp;</span> x <span class="sc">&lt;=</span> <span class="dv">45</span>) <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&#39;bus&#39;</span>, <span class="st">&#39;bike&#39;</span>, <span class="st">&#39;car&#39;</span>), <span class="at">size =</span> <span class="dv">1</span>)</span>
<span id="cb146-19"><a href="lin-reg.html#cb146-19" aria-hidden="true" tabindex="-1"></a>  <span class="cf">else</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&#39;bus&#39;</span>, <span class="st">&#39;car&#39;</span>), <span class="at">size =</span> <span class="dv">1</span>)</span>
<span id="cb146-20"><a href="lin-reg.html#cb146-20" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb146-21"><a href="lin-reg.html#cb146-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-22"><a href="lin-reg.html#cb146-22" aria-hidden="true" tabindex="-1"></a>time_lib <span class="ot">&lt;-</span> <span class="dv">5</span> <span class="sc">*</span> <span class="dv">60</span> <span class="sc">-</span> <span class="fl">0.7</span> <span class="sc">*</span> travel_time <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="fu">length</span>(travel_time), <span class="dv">0</span>, <span class="dv">20</span>)</span>
<span id="cb146-23"><a href="lin-reg.html#cb146-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-24"><a href="lin-reg.html#cb146-24" aria-hidden="true" tabindex="-1"></a>getsmarter_pop <span class="ot">&lt;-</span> <span class="fu">tibble</span>(student_id, gender, residence, transport, travel_time, time_lib)</span>
<span id="cb146-25"><a href="lin-reg.html#cb146-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb146-26"><a href="lin-reg.html#cb146-26" aria-hidden="true" tabindex="-1"></a>getsmarter_pop</span></code></pre></div>
<pre><code>## # A tibble: 12,000 × 6
##    student_id gender residence transport travel_time time_lib
##         &lt;int&gt; &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt;
##  1          1 f      urban     bus             15.1      294.
##  2          2 f      rural     bike            32.6      254.
##  3          3 f      urban     bike            19.3      231.
##  4          4 m      rural     car             35.9      245.
##  5          5 m      rural     bus             37.9      234.
##  6          6 f      urban     foot             6.59     303.
##  7          7 f      urban     bus             23.5      284.
##  8          8 m      rural     car             36.2      274.
##  9          9 m      urban     bike            24.3      299.
## 10         10 f      urban     bus             21.0      282.
## # … with 11,990 more rows</code></pre>
<p>We survey 200 students.</p>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="lin-reg.html#cb148-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">345</span>)</span>
<span id="cb148-2"><a href="lin-reg.html#cb148-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-3"><a href="lin-reg.html#cb148-3" aria-hidden="true" tabindex="-1"></a>survey_size <span class="ot">&lt;-</span> <span class="dv">200</span></span>
<span id="cb148-4"><a href="lin-reg.html#cb148-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb148-5"><a href="lin-reg.html#cb148-5" aria-hidden="true" tabindex="-1"></a>survey <span class="ot">&lt;-</span> <span class="fu">rep_sample_n</span>(getsmarter_pop, <span class="at">size =</span> survey_size, <span class="at">replace =</span> <span class="cn">FALSE</span>, <span class="at">reps =</span> <span class="dv">1</span>)</span></code></pre></div>
<div id="fit-a-simple-normal-regression-model" class="section level3" number="9.3.1">
<h3><span class="header-section-number">9.3.1</span> Fit a simple normal regression model</h3>
<p>We first check that the linear model makes sense and the relationship between the two variables is (approximately) linear.</p>
<div class="sourceCode" id="cb149"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb149-1"><a href="lin-reg.html#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> survey, <span class="fu">aes</span>(<span class="at">x =</span> travel_time, <span class="at">y =</span> time_lib)) <span class="sc">+</span></span>
<span id="cb149-2"><a href="lin-reg.html#cb149-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb149-3"><a href="lin-reg.html#cb149-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Travel time (min)&#39;</span>, <span class="at">y =</span> <span class="st">&#39;Time in the library (min)&#39;</span>)</span></code></pre></div>
<p><img src="environmental_stat_files/figure-html/unnamed-chunk-129-1.png" width="90%" /></p>
<p>This looks reasonably linear and we can proceed with the modelling.</p>
<p>To fit a linear model in R, we use the function <code>lm()</code>. The dependent and the independent varialbes are joined in a <code>formula</code> by a tilde sign <code>~</code>. You can also omit the word formula and just type <code>time_lib ~ travel_time</code>.</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="lin-reg.html#cb150-1" aria-hidden="true" tabindex="-1"></a>lin_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">formula =</span> time_lib <span class="sc">~</span> travel_time, <span class="at">data =</span> survey)</span></code></pre></div>
<p>That’s it 😄.</p>
<p>Let’s have a look at the estimated intercept and the slope. The function <code>get_regression_table</code> provides a tidy form of the model results and the function <code>kable()</code> layouts them nicely.</p>
<div class="sourceCode" id="cb151"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb151-1"><a href="lin-reg.html#cb151-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(lin_mod) <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std_error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p_value
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:right;">
302.094
</td>
<td style="text-align:right;">
2.282
</td>
<td style="text-align:right;">
132.387
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
297.594
</td>
<td style="text-align:right;">
306.594
</td>
</tr>
<tr>
<td style="text-align:left;">
travel_time
</td>
<td style="text-align:right;">
-0.766
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
-14.990
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.867
</td>
<td style="text-align:right;">
-0.665
</td>
</tr>
</tbody>
</table>
<p>The estimated intercept equals 302.094 minutes and the slope -0.766 minutes, respectively. We can write our model as:</p>
<p><span class="math display">\[\widehat{\text{time_lib}_i} = 302.094 - 0.766 \cdot \text{travel_time}_i + \varepsilon_i\]</span>
The model estimates a <code>time_lib</code> value for every student <span class="math inline">\(i\)</span>, with <span class="math inline">\(i\)</span> being an arbitrary student index running from 1 to 200 because we have surveyed 200 students. The “hat” above <span class="math inline">\(\text{time_lib}_i\)</span> indicates that this is an estimate. The estimated time in the library is the systematic component of the model, namely <span class="math inline">\(302.094 - 0.766 \cdot \text{travel_time}_i\)</span>. The difference of the actual time in the library and this estimated value is the error term or the residuum <span class="math inline">\(\varepsilon_i\)</span>.</p>
<p>To simplify our analysis, we put the original data, estimated values (also called fitted values) and the residuals in one tibble. The respective values can be extracted from the model object <code>lin_mod</code> with the functions <code>fitted()</code> and <code>residuals()</code>.</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="lin-reg.html#cb152-1" aria-hidden="true" tabindex="-1"></a>model_res <span class="ot">&lt;-</span> survey <span class="sc">%&gt;%</span></span>
<span id="cb152-2"><a href="lin-reg.html#cb152-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fitted =</span> <span class="fu">fitted</span>(lin_mod), <span class="at">residuals =</span> <span class="fu">residuals</span>(lin_mod))</span>
<span id="cb152-3"><a href="lin-reg.html#cb152-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb152-4"><a href="lin-reg.html#cb152-4" aria-hidden="true" tabindex="-1"></a>model_res</span></code></pre></div>
<pre><code>## # A tibble: 200 × 9
## # Groups:   replicate [1]
##    replicate student_id gender residence transport travel_time time_lib fitted
##        &lt;int&gt;      &lt;int&gt; &lt;chr&gt;  &lt;chr&gt;     &lt;chr&gt;           &lt;dbl&gt;    &lt;dbl&gt;  &lt;dbl&gt;
##  1         1       1623 m      urban     foot             7.06     299.   297.
##  2         1       9171 m      urban     bike            11.3      278.   293.
##  3         1      10207 f      rural     bus            107.       199.   220.
##  4         1       3506 f      urban     bus             25.0      326.   283.
##  5         1       8892 f      urban     bus             28.1      259.   281.
##  6         1       5460 m      urban     bus             23.6      299.   284.
##  7         1       6120 f      urban     bus             20.0      268.   287.
##  8         1        865 f      urban     bike            26.6      290.   282.
##  9         1      11586 m      rural     bus            114.       207.   215.
## 10         1       8153 f      urban     foot             8.06     297.   296.
## # … with 190 more rows, and 1 more variable: residuals &lt;dbl&gt;</code></pre>
<p>Let’s have a look at the residuals and the fitted values.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="lin-reg.html#cb154-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(model_res, <span class="fu">aes</span>(<span class="at">x =</span> travel_time, <span class="at">y =</span> time_lib)) <span class="sc">+</span></span>
<span id="cb154-2"><a href="lin-reg.html#cb154-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_segment</span>(<span class="fu">aes</span>(<span class="at">xend =</span> travel_time, <span class="at">yend =</span> fitted, <span class="at">lty =</span> <span class="st">&#39;Residuals&#39;</span>), <span class="at">alpha =</span> <span class="fl">0.2</span>)  <span class="sc">+</span> </span>
<span id="cb154-3"><a href="lin-reg.html#cb154-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_abline</span>(<span class="at">intercept =</span> <span class="fu">coef</span>(lin_mod)[<span class="dv">1</span>], <span class="at">slope =</span> <span class="fu">coef</span>(lin_mod)[<span class="dv">2</span>], <span class="at">color =</span> <span class="st">&quot;lightblue&quot;</span>) <span class="sc">+</span></span>
<span id="cb154-4"><a href="lin-reg.html#cb154-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">col =</span> <span class="st">&#39;observed&#39;</span>)) <span class="sc">+</span></span>
<span id="cb154-5"><a href="lin-reg.html#cb154-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">y =</span> fitted, <span class="at">col =</span> <span class="st">&#39;fitted&#39;</span>), <span class="at">shape =</span> <span class="dv">1</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb154-6"><a href="lin-reg.html#cb154-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Travel time (min)&#39;</span>, <span class="at">y =</span> <span class="st">&#39;Time in the library (min)&#39;</span>) <span class="sc">+</span></span>
<span id="cb154-7"><a href="lin-reg.html#cb154-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">name =</span> <span class="st">&#39;&#39;</span>, <span class="at">values =</span> <span class="fu">c</span>(<span class="at">observed =</span> <span class="st">&#39;black&#39;</span>, <span class="at">fitted =</span> <span class="st">&#39;blue&#39;</span>), <span class="at">breaks =</span> <span class="fu">c</span>(<span class="st">&#39;observed&#39;</span>, <span class="st">&#39;fitted&#39;</span>), <span class="at">label =</span> <span class="fu">c</span>(<span class="st">&#39;Observed values&#39;</span>, <span class="st">&#39;Fitted values&#39;</span>)) <span class="sc">+</span></span>
<span id="cb154-8"><a href="lin-reg.html#cb154-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_linetype_manual</span>(<span class="at">name =</span> <span class="st">&#39;&#39;</span>, <span class="at">values =</span> (<span class="st">&#39;Residuals&#39;</span> <span class="ot">=</span> <span class="st">&#39;solid&#39;</span>)) <span class="sc">+</span></span>
<span id="cb154-9"><a href="lin-reg.html#cb154-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">&#39;bottom&#39;</span>)</span></code></pre></div>
<p><img src="environmental_stat_files/figure-html/unnamed-chunk-133-1.png" width="90%" /></p>
</div>
<div id="model-assumptions" class="section level3" number="9.3.2">
<h3><span class="header-section-number">9.3.2</span> Model assumptions</h3>
<p>Before we interpret the meaning of the model parameters <em>intercept</em> and <em>slope</em>, we have to check the model assumptions. We already saw that the relationship is reasonably linear. Let’s look at the rest of the assumptions.</p>
<p><strong>Independent residuals</strong>. This is difficult to check and should come with the study design. If you have like in our example independently surveyed students, you can reasonably assume that the both, the data and the residuals are independent. Conversely it means that you cannot use a normal linear regression model for time depenend data (time series) or spatially dependent data. The line you fit will still be correct, but the confidence intervals won’t.</p>
<p><strong>Normal residuals.</strong> To check for normality of residuals, we use a graphical tool, namely the so-called qq-plot. It compares random data from a normal distribution with our residuals. If the data fall on strait line (at least approximately) then we can conclude that our residuals are normally distributed.</p>
<div class="sourceCode" id="cb155"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb155-1"><a href="lin-reg.html#cb155-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(model_res, <span class="fu">aes</span>(<span class="at">sample =</span> residuals)) <span class="sc">+</span> </span>
<span id="cb155-2"><a href="lin-reg.html#cb155-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq</span>() <span class="sc">+</span> </span>
<span id="cb155-3"><a href="lin-reg.html#cb155-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">stat_qq_line</span>() <span class="sc">+</span></span>
<span id="cb155-4"><a href="lin-reg.html#cb155-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Quantiles of the normal distribution&#39;</span>,</span>
<span id="cb155-5"><a href="lin-reg.html#cb155-5" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">&#39;Qauntiles of the residuals&#39;</span>)</span></code></pre></div>
<p><img src="environmental_stat_files/figure-html/unnamed-chunk-134-1.png" width="90%" /></p>
<p>This looks good 😄. You will need some practice to judge the qq-plots. You need to worry if you see large deviations from the line for small and large values.</p>
<p><strong>Equal variance and zero mean.</strong> For the last assumption, we plot the residuals versus fitted values. It is important that the residuals remain (approximately) equally large for small and large fitted values and fluctuate around zero.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="lin-reg.html#cb156-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> model_res, <span class="fu">aes</span>(<span class="at">x =</span> fitted, <span class="at">y =</span> residuals)) <span class="sc">+</span> </span>
<span id="cb156-2"><a href="lin-reg.html#cb156-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb156-3"><a href="lin-reg.html#cb156-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_hline</span>(<span class="at">yintercept=</span><span class="dv">0</span>, <span class="at">col =</span> <span class="st">&#39;red&#39;</span>) <span class="sc">+</span> </span>
<span id="cb156-4"><a href="lin-reg.html#cb156-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">&#39;Fitted values&#39;</span>, <span class="at">y =</span> <span class="st">&#39;Residuals&#39;</span>)</span></code></pre></div>
<p><img src="environmental_stat_files/figure-html/unnamed-chunk-135-1.png" width="90%" /></p>
<p>We have slightly larger residuals for larger fitted values. However, we also have more larger than smaller fitted values (i.e. travel times). This distorts the picture a bit. Overall, there is no serious problem there.</p>
</div>
<div id="interprete-your-model" class="section level3" number="9.3.3">
<h3><span class="header-section-number">9.3.3</span> Interprete your model</h3>
<p>We can conclude that our model meets all the assumptions. Therefore, we can interpret the estimated parameters and their confidence intervals now.</p>
<div class="sourceCode" id="cb157"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb157-1"><a href="lin-reg.html#cb157-1" aria-hidden="true" tabindex="-1"></a><span class="fu">get_regression_table</span>(lin_mod) <span class="sc">%&gt;%</span> <span class="fu">kable</span>()</span></code></pre></div>
<table>
<thead>
<tr>
<th style="text-align:left;">
term
</th>
<th style="text-align:right;">
estimate
</th>
<th style="text-align:right;">
std_error
</th>
<th style="text-align:right;">
statistic
</th>
<th style="text-align:right;">
p_value
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
intercept
</td>
<td style="text-align:right;">
302.094
</td>
<td style="text-align:right;">
2.282
</td>
<td style="text-align:right;">
132.387
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
297.594
</td>
<td style="text-align:right;">
306.594
</td>
</tr>
<tr>
<td style="text-align:left;">
travel_time
</td>
<td style="text-align:right;">
-0.766
</td>
<td style="text-align:right;">
0.051
</td>
<td style="text-align:right;">
-14.990
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
-0.867
</td>
<td style="text-align:right;">
-0.665
</td>
</tr>
</tbody>
</table>
<p>We see that the time a student spend in the library decreases with increasing travel time. More precisely, if the travel time increases by one minute, the time spent in the library changes by -0.8 [-0.9, -0.7]. The confidence interval is narrow. This means that the estimation is precise.</p>
<p>Now, we need to frame our result. A decrease by less than a minute per minute travel time sounds rather small. However, if a student needs one hour more to come to the university, she spends roughly 45 minutes less in the library. Basically, the time spent for travelling cannot be spent working in the library. Stated like this, the result is important for students’ time management.</p>
</div>
</div>
<div id="practice-on-your-own-8" class="section level2" number="9.4">
<h2><span class="header-section-number">9.4</span> Practice on your own!</h2>
<ol class="exercises">
<ol style="list-style-type: decimal">
<li>Predictors do not need to be numeric. Work through Chapter 5.2 in <span class="citation">Ismay and Kim (<a href="literature-1.html#ref-ModernDive" role="doc-biblioref">2021</a>)</span> to see an example of a categorical predictor.</li>
</ol>
</ol>
</div>
<div id="reading-assignment-7" class="section level2" number="9.5">
<h2><span class="header-section-number">9.5</span> Reading assignment</h2>
<p>Chapter 5 in <span class="citation">Ismay and Kim (<a href="literature-1.html#ref-ModernDive" role="doc-biblioref">2021</a>)</span></p>
<!-- ## Turning in your work -->
<!-- - Save your R Notebook as an *.Rmd file.  -->
<!-- - Upload your R Notebook to ILIAS. You don't need to upload the .nb.html file. You will find an upload option in today's session. -->
<!-- - You should receive a solution file after your upload. **Be sure to upload before the deadline!** -->

</div>
</div>
  </main>

  <div class="col-md-3 col-lg-2 d-none d-md-block sidebar sidebar-chapter">
    <nav id="toc" data-toggle="toc" aria-label="On this page">
      <h2>On this page</h2>
      <div id="book-on-this-page"></div>

      <div class="book-extra">
        <ul class="list-unstyled">
          <li><a id="book-source" href="#">View source <i class="fab fa-github"></i></a></li>
          <li><a id="book-edit" href="#">Edit this page <i class="fab fa-github"></i></a></li>
        </ul>
      </div>
    </nav>
  </div>

</div>
</div> <!-- .container -->

<footer class="bg-primary text-light mt-5">
  <div class="container"><div class="row">

  <div class="col-12 col-md-6 mt-3">
    <p>"<strong>Environmental Statistics</strong>: Summer term 2022" was written by Christina Bogner. It was last built on 2022-06-20.</p>
  </div>

  <div class="col-12 col-md-6 mt-3">
    <p>This book was built by the <a class="text-light" href="https://bookdown.org">bookdown</a> R package.</p>
  </div>

</div></div>
</footer>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
<script type="text/x-mathjax-config">const popovers = document.querySelectorAll('a.footnote-ref[data-toggle="popover"]');
for (let popover of popovers) {
  const div = document.createElement('div');
  div.setAttribute('style', 'position: absolute; top: 0, left:0; width:0, height:0, overflow: hidden; visibility: hidden;');
  div.innerHTML = popover.getAttribute('data-content');

  var has_math = div.querySelector("span.math");
  if (has_math) {
    document.body.appendChild(div);
    MathJax.Hub.Queue(["Typeset", MathJax.Hub, div]);
    MathJax.Hub.Queue(function() {
      popover.setAttribute('data-content', div.innerHTML);
      document.body.removeChild(div);
    })
  }
}
</script>
</body>

</html>
